/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */

#include <iostream>

using namespace std;

int fibonacci(int n) {
    if (n == 0 || n == 1 || n == 2) {
        return n;
    }
    return fibonacci(n-1) + fibonacci(n-2);
}

int main(void)
{
    int i = 0, sum = 0, fibo = 0;

    for (; fibo <= 4000000; fibo = fibonacci(i++))
    {
        if (!(fibo % 2))
        {
            sum += fibo;
        }
    }
    cout << sum << endl;
}
